# Playbook de hardening del servicio SSH
- name: Hardening SSH en servidores
  hosts: servers
  become: yes

  tasks:

    # Desactiva login por contraseña
    # Obliga a usar claves SSH (más seguro)
    - name: Desactivar autenticación por contraseña
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication no"

    # Evita acceso directo del usuario root por SSH
    - name: Desactivar login de root por SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin no"

    # Reinicia el servicio SSH para aplicar cambios
    - name: Reiniciar SSH
      service:
        name: ssh
        state: restarted
